### ISSUE TITLE
ItemSketch throws errors and kicks players on Dedicated Server

### ISSUE THREAD

**Issue by CovertJaguar** [MightyPirates/Architect#19]
In 1.0.2-1.0.4 for 1.10.2

Specifically player.getPositionEyes() does not exist on the server.

```
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
	at li.cil.architect.util.PlayerUtils.getLookAtPos(PlayerUtils.java:26) ~[PlayerUtils.class:?]
	at li.cil.architect.common.item.ItemSketch.func_77659_a(ItemSketch.java:111) ~[ItemSketch.class:?]
```
```
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
	at li.cil.architect.common.item.ItemSketch.onUsingTick(ItemSketch.java:132) ~[ItemSketch.class:?]
```

**Comment by fnuecke** [comment]
Ugh, thanks a lot! This isn't client-only in 1.11, which is how this snuck in -.-
